import {RF} from './responsive';

export const THEME = {
  COLORS: {
    primaryBackground: '#1B232E',
    primaryBackgroundLower: 'rgba(19, 10, 53, 1)',
    secondaryBackground: '#242E42',
    accentBlue: '#27A3E3',
    lightBlue: '#209EE2',
    textLight: '#928FA3',
    green: '#1CD983',
    blue: '#4C7BF6',
    red: '#FF0000',
    countRed: '#FD6969',
    gold: '#F89F36',
    white: '#fff',
    black: '#000',
    gradientTopColor: '#269CDD',
    gradientBottomColor: '#235DAC',
    dottedBorder: '#20FFFF',
    tabColor: '#242E42',
    darkGrey: '#323943',
    tintBlue: '#00A8FF',
  },
  FONTS: {
    SIZE: {
      XXLARGE: RF(32),
      XLARGE: RF(24),
      LARGE: RF(20),
      MEDIUM: RF(18),
      SMALL: RF(16),
      XSMALL: RF(14),
      XXSMALL: RF(12),
      XXXSMALL: RF(10),
    },
    TYPE: {
      LIGHT: 'Montserrat-Light',
      REGULAR: 'Montserrat-Regular',
      MEDIUM: 'Montserrat-Medium',
      SEMIBOLD: 'Montserrat-SemiBold',
      BOLD: 'Montserrat-Bold',
    },
  },
  MARGIN: {
    SUPERLOW: RF(2),
    VERYLOW: RF(4),
    LOW: RF(8),
    NORMAL: RF(16),
    HIGH: RF(24),
    VERYHIGH: RF(32),
    SUPERHIGH: RF(48),
    NOVAHIGH: RF(60),
  },
  PADDING: {
    SUPERLOW: RF(2),
    VERYLOW: RF(4),
    LOW: RF(8),
    MID_LOW: RF(12),
    NORMAL: RF(16),
    HIGH: RF(24),
    VERYHIGH: RF(32),
    SUPERHIGH: RF(48),
  },
  RADIUS: {
    BOX: RF(10),
    SMALLBOX: RF(5),
    OVAL: RF(24),
  },
};
