const ICONS = {
  LOGO: require('./icons/logoTransparent.png'),
  QRCODE: require('./icons/qrcode.png'),
  QRFRAME: require('./icons/qrframe.png'),
  QR_BUTTON: require('./icons/scanBtn.png'),
  PASTE_BUTTON: require('./icons/paste.png'),
  ENABLE_MERCHANT: require('./icons/EnableMechant.png'),
  LANGUAGE: require('./icons/language.png'),
  ADD_CONTACT: require('./icons/AddContacts.png'),
  COIN_ACCEPTANCE: require('./icons/coinAcceptance.png'),
  BACKUP_WALLET: require('./icons/backupPhrase.png'),
  SWITCH_BUYER: require('./icons/SwitchBuyer.png'),
  PROTECTION_FEE: require('./icons/ProtectionFee.png'),
  THUMB: require('./icons/thumb.png'),
  CART: require('./icons/cart.png'),
  POS: require('./icons/pos.png'),
  WALLET: require('./icons/wallet.png'),
  SETTINGS: require('./icons/settings.png'),
  SENT: require('./icons/sent.png'),
  RECEIVED: require('./icons/received.png'),
  SEND: require('./icons/sendT.png'),
  RECEIVEDT: require('./icons/receiveT.png'),
  COPY: require('./icons/copy.png'),
  SUCCESS: require('./icons/success.png'),
  FAILED: require('./icons/fail.png'),
  PIN_LOCATION: require('./icons/pinLocation.png'),
  LOCATION: require('./icons/location.png'),
  SEARCH: require('./icons/search.png'),
  CROSS: require('./icons/cross.png'),
  TICK: require('./icons/tick.png'),
  PLUS: require('./icons/plus.png'),
  MAP_LOCATION: require('./icons/mapLocation.png'),
  IMAGE_PICKER: require('./icons/imagePicker.png'),
  STORE_LOCATION: require('./icons/addStore.png'),
  //Temp Images
  DUMMY_MAP: require('./icons/dummyMap.png'),
  DUMMY_IMAGE: require('./icons/dummyProduct.png'),
  BAG1: require('./icons/bag1.png'),
  BAG2: require('./icons/bag2.png'),
  BAG3: require('./icons/bag3.png'),
  DUMMY_MINI: require('./icons/miniImage.png'),
  //Status Icons
  STATUS_COMPLETED: require('./statusIcons/completed.png'),
  STATUS_CONFIRMING: require('./statusIcons/confirming.png'),
  STATUS_ERROR: require('./statusIcons/error.png'),
  STATUS_PENDING: require('./statusIcons/pending.png'),
  //Iamges
  QR_OVERLAY: require('./images/qrOverlay.png'),
  //Settings
  PHRASE_EYE: require('./icons/phraseEye.png'),
  EYE: require('./icons/eye.png'),
  EYE_OFF: require('./icons/eye-off.png'),
  placeholderCoin: require('./icons/placeholderCoin.png'),
  historyIcon: require('./icons/history.png'),
  sendIcon: require('./icons/sentLight.png'),
};

const ANIMATIONS = {
  comingSoon: require('./animations/comingSoon.json'),
  comingSoonSpanish: require('./animations/comingSoonSpanish.json'),
};

export {ICONS, ANIMATIONS};
